"use client";
import {useEffect,useMemo,useState} from "react";
import {ArrowRight,Check,Download,Eye,RotateCcw,ShieldCheck,Trash2} from "lucide-react";
type Trace={opened:number[];selected:number|null;changes:number;startedAt:number;decidedAt:number|null};
type Session={startedAt:string;completedAt?:string;traces:Record<string,Trace>};
type WebTool={name:string;title:string;description:string;inputSchema:Record<string,unknown>;annotations:Record<string,boolean>;execute:(input:unknown)=>unknown};
type ModelContext={registerTool:(tool:WebTool,options?:{signal:AbortSignal})=>void|Promise<void>};
const scenes=[
 {id:"message",no:"01",place:"Wiadomość",fact:"Osoba, z którą zwykle piszesz wieczorami, przeczytała Twoją wiadomość. Od czterech godzin nie odpowiedziała.",prompt:"Co wydaje Ci się najbardziej prawdopodobne?",answers:[["Potrzebuje dystansu","Brak odpowiedzi może być celowym wycofaniem albo unikaniem trudnego tematu."],["Jest czymś zajęta","Przeczytanie wiadomości nie mówi nic o czasie, energii ani warunkach do odpowiedzi."],["Nie wie, co napisać","Cisza może wynikać z niepewności, troski o słowa albo potrzeby namysłu."]]},
 {id:"meeting",no:"02",place:"Spotkanie",fact:"Podczas rozmowy jedna osoba kilkukrotnie zerka na telefon, ale zadaje Ci dalsze pytania i pamięta wcześniejsze szczegóły.",prompt:"Jak odczytujesz jej zachowanie?",answers:[["Rozmowa ją nudzi","Telefon może być sygnałem spadku uwagi lub próbą skrócenia spotkania."],["Czeka na ważną informację","Podzielona uwaga może mieć zewnętrzną przyczynę niezwiązaną z Tobą."],["Tak reguluje napięcie","Krótki ruch w stronę telefonu może pomagać jej zebrać myśli w intensywnej rozmowie."]]},
 {id:"feedback",no:"03",place:"Praca",fact:"Po prezentacji przełożona mówi: „To interesujący kierunek. Wróćmy do niego jutro”, po czym kończy spotkanie wcześniej.",prompt:"Co słyszysz między słowami?",answers:[["To uprzejma odmowa","Ogólna pochwała i odroczenie mogą łagodzić negatywną ocenę."],["Pomysł wymaga namysłu","Decyzja może mieć konsekwencje, których nie da się uczciwie ocenić od razu."],["Zmieniły się jej priorytety","Wcześniejszy koniec spotkania może dotyczyć czegoś pilnego poza prezentacją."]]},
 {id:"invitation",no:"04",place:"Zaproszenie",fact:"Znajoma reaguje sercem na zdjęcia ze wspólnego wyjazdu, ale nie odpowiada na propozycję kolejnego spotkania.",prompt:"Która interpretacja pojawia się pierwsza?",answers:[["Lubi wspomnienie, nie relację","Reakcja na przeszłość nie musi oznaczać gotowości na dalszy kontakt."],["Nie zna jeszcze terminu","Brak decyzji może wynikać z kalendarza, nie z poziomu sympatii."],["Chce odpowiedzieć później","Lekka reakcja jest szybka, a ustalenie spotkania wymaga większego zaangażowania."]]},
 {id:"silence",no:"05",place:"Grupa",fact:"Kiedy przedstawiasz swój pomysł, dwie osoby milczą. Chwilę później jedna z nich rozwija inny wątek bez odniesienia do Twojej propozycji.",prompt:"Co mogło wydarzyć się w tej ciszy?",answers:[["Pomysł został odrzucony","Zmiana tematu może być niebezpośrednim sygnałem braku poparcia."],["Grupa nie podjęła decyzji","Milczenie nie jest głosem przeciw. Pomysł mógł pozostać bez odpowiedzi."],["Ktoś nie zauważył związku","Nowy wątek mógł być próbą rozwinięcia rozmowy, choć zabrakło wyraźnego łącznika."]]}
] as const;
const fresh=():Session=>({startedAt:new Date().toISOString(),traces:Object.fromEntries(scenes.map(s=>[s.id,{opened:[],selected:null,changes:0,startedAt:Date.now(),decidedAt:null}]))});
function analyze(s:Session){const t=Object.values(s.traces),opened=t.reduce((a,x)=>a+x.opened.length,0),changes=t.reduce((a,x)=>a+x.changes,0),ds=t.filter(x=>x.decidedAt).map(x=>(x.decidedAt!-x.startedAt)/1000),avg=ds.length?Math.round(ds.reduce((a,b)=>a+b,0)/ds.length):0,all=t.filter(x=>x.opened.length===3).length;return[
 {title:"Hipoteza A: ostrożność poznawcza",claim:opened>=12?"Sprawdzasz wiele możliwości, zanim uznasz jedną za najbardziej prawdopodobną.":"Ograniczasz liczbę bodźców, żeby nie dopowiadać historii bez potrzeby.",evidence:"Otwarte interpretacje: "+opened+"/15. Średni czas do decyzji: "+avg+" s.",limit:"Nie wiemy, czy wynikało to z ostrożności, ciekawości, sposobu używania interfejsu czy chęci ukończenia eksperymentu."},
 {title:"Hipoteza B: szybka intuicja",claim:avg<18?"Szybko budujesz robocze wyjaśnienie i traktujesz je jako wystarczające do dalszego działania.":"Dłuższy namysł może oznaczać, że pierwsza intuicja była silna, ale została poddana kontroli.",evidence:"Decyzja zajmowała średnio "+avg+" s. Pierwszą odpowiedź zmieniono "+changes+" razy.",limit:"Czas reakcji nie mierzy pewności. Mogły wpłynąć na niego długość tekstu, przerwa, zmęczenie albo znajomość sytuacji."},
 {title:"Hipoteza C: elastyczność albo podatność",claim:changes>=2?"Nowe informacje potrafią zmienić Twój osąd. To może być elastyczność, ale równie dobrze brak stabilnego kryterium.":"Trzymasz się pierwszego wyboru. To może być konsekwencja, ale równie dobrze efekt zakotwiczenia.",evidence:"Liczba zmian decyzji: "+changes+". W "+all+" scenach otwarto wszystkie możliwości.",limit:"Ten sam wzorzec zachowania wspiera dwie przeciwne opowieści. Bez celu, emocji i kontekstu żadna nie jest diagnozą."}]}
export default function Home(){
 const [session,setSession]=useState<Session>(fresh),[index,setIndex]=useState(0),[done,setDone]=useState(false),[ready,setReady]=useState(false);const scene=scenes[index],trace=session.traces[scene.id];
 useEffect(()=>{const raw=localStorage.getItem("interpretation-mirror-session");if(raw)try{const x=JSON.parse(raw);setSession(x.session);setIndex(Math.min(x.index,4));setDone(x.done)}catch{localStorage.removeItem("interpretation-mirror-session")}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem("interpretation-mirror-session",JSON.stringify({session,index,done}))},[session,index,done,ready]);
 const change=(fn:(x:Trace)=>Trace)=>setSession(s=>({...s,traces:{...s.traces,[scene.id]:fn(s.traces[scene.id])}}));
 const open=(i:number)=>change(x=>({...x,opened:x.opened.includes(i)?x.opened:[...x.opened,i]}));
 const choose=(i:number)=>change(x=>({...x,opened:x.opened.includes(i)?x.opened:[...x.opened,i],selected:i,changes:x.selected!==null&&x.selected!==i?x.changes+1:x.changes,decidedAt:Date.now()}));
 const next=()=>{if(trace.selected===null)return;if(index===4){setSession(s=>({...s,completedAt:new Date().toISOString()}));setDone(true)}else setIndex(i=>i+1)};
 const reset=()=>{localStorage.removeItem("interpretation-mirror-session");setSession(fresh());setIndex(0);setDone(false)};
 const interpretations=useMemo(()=>analyze(session),[session]);
 const exportData=()=>{const blob=new Blob([JSON.stringify({note:"Zapis eksperymentu. Nie jest profilem ani diagnozą.",session,interpretations},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="interpretation-mirror-"+new Date().toISOString().slice(0,10)+".json";a.click();URL.revokeObjectURL(a.href)};
 useEffect(()=>{const context=(document as Document&{modelContext?:ModelContext}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();const register=(tool:WebTool)=>{try{void Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{})}catch{}};
  register({name:"read_experiment_progress",title:"Sprawdź postęp",description:"Zwraca bieżący etap eksperymentu bez ujawniania dodatkowych danych.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({scene:done?5:index+1,total:5,completed:done})});
  register({name:"reset_experiment",title:"Wyczyść eksperyment",description:"Usuwa lokalny przebieg i rozpoczyna eksperyment od pierwszej sytuacji.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:()=>{reset();return{reset:true,scene:1}}});
  return()=>controller.abort()},[index,done]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(done)return;if(["1","2","3"].includes(e.key)){const i=+e.key-1;trace.opened.includes(i)?choose(i):open(i)}if(e.key==="Enter"&&trace.selected!==null)next()};addEventListener("keydown",key);return()=>removeEventListener("keydown",key)});
 if(!ready)return <main className="loading">Przygotowuję lustro…</main>;
 return <main><header className="topbar"><a className="brand" href="#main"><span className="brand-mark"><span/></span>Interpretation Mirror</a><div className="privacy"><ShieldCheck size={16}/> Dane zostają tutaj</div></header><div className="progress"><span style={{width:(done?100:(index+1)*20)+"%"}}/></div>
 <section id="main" className={done?"workspace results-workspace":"workspace"}>{!done?<><aside className="steps"><p className="eyebrow">Pięć sytuacji</p><ol>{scenes.map((s,i)=><li key={s.id} className={i===index?"active":i<index?"past":""}><span>{i<index?<Check size={14}/>:s.no}</span><div><strong>{s.place}</strong><small>{i===index?"teraz":i<index?"gotowe":"przed Tobą"}</small></div></li>)}</ol><p className="side-note">Nie szukamy poprawnej odpowiedzi. Obserwujemy, jak powstaje wniosek.</p></aside>
 <article className="card"><div className="heading"><div><p className="eyebrow">Sytuacja {scene.no} · {scene.place}</p><h1>Tylko tyle wiadomo.</h1></div><span>{index+1} / 5</span></div><blockquote>{scene.fact}</blockquote><h2>{scene.prompt}</h2><p className="hint">Otwórz tyle możliwości, ile potrzebujesz. Wybór możesz zmienić.</p>
 <div className="answers">{scene.answers.map((a,i)=>{const isOpen=trace.opened.includes(i),selected=trace.selected===i;return <section key={a[0]} className={"answer "+(isOpen?"open ":"")+(selected?"selected":"")}><button className="answer-head" onClick={()=>open(i)} aria-expanded={isOpen}><span>{i+1}</span><strong>{isOpen?a[0]:"Odsłoń możliwe odczytanie"}</strong><Eye size={18}/></button>{isOpen&&<div className="answer-body"><p>{a[1]}</p><button onClick={()=>choose(i)} aria-pressed={selected}>{selected?<><Check size={16}/> To mój obecny wybór</>:"To wydaje mi się najbardziej prawdopodobne"}</button></div>}</section>})}</div>
 <footer className="card-footer"><p>{trace.changes?"Zmiany decyzji w tej scenie: "+trace.changes:"Możesz wrócić do każdej odsłoniętej odpowiedzi."}</p><button className="primary" onClick={next} disabled={trace.selected===null}>{index===4?"Zobacz trzy interpretacje":"Następna sytuacja"}<ArrowRight size={18}/></button></footer></article></>:
 <section className="results"><div className="result-intro"><p className="eyebrow">To samo zachowanie. Trzy opowieści.</p><h1>Lustro nie wie, kim jesteś.</h1><p>Widziało tylko kilka kliknięć, kolejność otwierania odpowiedzi i czas. Na tej podstawie potrafi zbudować wiarygodne, sprzeczne narracje.</p></div>
 <div className="result-grid">{interpretations.map((x,i)=><article className={"result-card r"+(i+1)} key={x.title}><span>0{i+1}</span><h2>{x.title}</h2><p className="claim">{x.claim}</p><div><strong>Co to wspiera</strong><p>{x.evidence}</p></div><div className="limit"><strong>Czego nie wiemy</strong><p>{x.limit}</p></div></article>)}</div>
 <div className="conclusion"><span>≠</span><div><h2>Dane to nie znaczenie</h2><p>Ślad zachowania staje się interpretacją dopiero po dodaniu kontekstu. Tutaj kontekstu celowo brakuje.</p></div></div><div className="actions"><button className="primary" onClick={exportData}><Download size={17}/> Eksportuj przebieg</button><button className="secondary" onClick={reset}><RotateCcw size={17}/> Zacznij od nowa</button><button className="delete" onClick={reset}><Trash2 size={17}/> Usuń dane</button></div></section>}</section>
 <footer className="page-footer"><p>To eksperyment o granicach wnioskowania, nie test osobowości.</p><p className="keys">Klawiatura: <kbd>1</kbd> <kbd>2</kbd> <kbd>3</kbd> otwórz / wybierz · <kbd>Enter</kbd> dalej</p></footer></main>
}
